In [1]:
import fastf1
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

In [2]:
# Enable FastF1 caching
fastf1.Cache.enable_cache("f1_cache")

# Load FastF1 2024 Australian GP race session
session_2024 = fastf1.get_session(2024, 3, "R")
session_2024.load()

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']

In [12]:
# Extract lap times
laps_2024 = session_2024.laps[["Driver", "LapTime"]].copy()
laps_2024.dropna(subset=["LapTime"], inplace=True)
laps_2024["LapTime (s)"] = laps_2024["LapTime"].dt.total_seconds()

laps_2024

    Driver                LapTime  LapTime (s)
0      VER 0 days 00:01:27.458000       87.458
1      VER 0 days 00:01:24.099000       84.099
2      VER 0 days 00:01:23.115000       83.115
4      GAS 0 days 00:01:37.304000       97.304
5      GAS 0 days 00:01:24.649000       84.649
..     ...                    ...          ...
993    PIA 0 days 00:01:20.199000       80.199
994    PIA 0 days 00:01:20.754000       80.754
995    PIA 0 days 00:01:20.357000       80.357
996    PIA 0 days 00:01:25.255000       85.255
997    PIA 0 days 00:02:04.363000      124.363

[995 rows x 3 columns]

In [5]:
# 2025 Qualifying Data
qualifying_2025 = pd.DataFrame({
    "Driver": ["Lando Norris", "Oscar Piastri", "Max Verstappen", "George Russell", "Yuki Tsunoda",
               "Alexander Albon", "Charles Leclerc", "Lewis Hamilton", "Pierre Gasly", "Carlos Sainz", "Fernando Alonso", "Lance Stroll"],
    "QualifyingTime (s)": [75.096, 75.180, 75.481, 75.546, 75.670,
                           75.737, 75.755, 75.973, 75.980, 76.062, 76.4, 76.5]
})

In [6]:
qualifying_2025

             Driver  QualifyingTime (s)
0      Lando Norris              75.096
1     Oscar Piastri              75.180
2    Max Verstappen              75.481
3    George Russell              75.546
4      Yuki Tsunoda              75.670
5   Alexander Albon              75.737
6   Charles Leclerc              75.755
7    Lewis Hamilton              75.973
8      Pierre Gasly              75.980
9      Carlos Sainz              76.062
10  Fernando Alonso              76.400
11     Lance Stroll              76.500

In [7]:
# Map full names to FastF1 3-letter codes
driver_mapping = {
    "Lando Norris": "NOR", "Oscar Piastri": "PIA", "Max Verstappen": "VER", "George Russell": "RUS",
    "Yuki Tsunoda": "TSU", "Alexander Albon": "ALB", "Charles Leclerc": "LEC", "Lewis Hamilton": "HAM",
    "Pierre Gasly": "GAS", "Carlos Sainz": "SAI", "Lance Stroll": "STR", "Fernando Alonso": "ALO"
}

In [8]:
qualifying_2025["DriverCode"] = qualifying_2025["Driver"].map(driver_mapping)
qualifying_2025

             Driver  QualifyingTime (s) DriverCode
0      Lando Norris              75.096        NOR
1     Oscar Piastri              75.180        PIA
2    Max Verstappen              75.481        VER
3    George Russell              75.546        RUS
4      Yuki Tsunoda              75.670        TSU
5   Alexander Albon              75.737        ALB
6   Charles Leclerc              75.755        LEC
7    Lewis Hamilton              75.973        HAM
8      Pierre Gasly              75.980        GAS
9      Carlos Sainz              76.062        SAI
10  Fernando Alonso              76.400        ALO
11     Lance Stroll              76.500        STR

In [ ]:
merged_data = qualifying_2025.merge(laps_2024, left_on="DriverCode", right_on="Driver")
# pd.set_option('display.max_rows', None)  # Show all rows
# pd.set_option('display.max_columns', None)  # Show all columns
# pd.set_option('display.width', None)  # No line wrapping

# print(df)
merged_data

,Driver_x,QualifyingTime (s),DriverCode,Driver_y,LapTime,LapTime (s)
0,Lando Norris,75.096,NOR,NOR,0 days 00:01:29.784000,89.784
1,Lando Norris,75.096,NOR,NOR,0 days 00:01:23.183000,83.183
2,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.656000,82.656
3,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.609000,82.609
4,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.685000,82.685
5,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.632000,82.632
6,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.744000,82.744
7,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.630000,82.630
8,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.727000,82.727
9,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.695000,82.695
10,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.936000,82.936
11,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.814000,82.814
12,Lando Norris,75.096,NOR,NOR,0 days 00:01:23.153000,83.153
13,Lando Norris,75.096,NOR,NOR,0 days 00:01:38.099000,98.099
14,Lando Norris,75.096,NOR,NOR,0 days 00:01:28.205000,88.205
15,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.936000,81.936
16,Lando Norris,75.096,NOR,NOR,0 days 00:01:38.388000,98.388
17,Lando Norris,75.096,NOR,NOR,0 days 00:01:27.418000,87.418
18,Lando Norris,75.096,NOR,NOR,0 days 00:01:22.356000,82.356
19,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.642000,81.642
20,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.907000,81.907
21,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.749000,81.749
22,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.745000,81.745
23,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.562000,81.562
24,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.713000,81.713
25,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.611000,81.611
26,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.976000,81.976
27,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.837000,81.837
28,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.864000,81.864
29,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.982000,81.982
30,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.848000,81.848
31,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.574000,81.574
32,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.692000,81.692
33,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.769000,81.769
34,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.510000,81.510
35,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.446000,81.446
36,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.662000,81.662
37,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.518000,81.518
38,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.901000,81.901
39,Lando Norris,75.096,NOR,NOR,0 days 00:01:36.023000,96.023
40,Lando Norris,75.096,NOR,NOR,0 days 00:01:26.576000,86.576
41,Lando Norris,75.096,NOR,NOR,0 days 00:01:21.025000,81.025
42,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.652000,80.652
43,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.613000,80.613
44,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.620000,80.620
45,Lando Norris,75.096,NOR,NOR,0 days 00:01:19.971000,79.971
46,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.188000,80.188
47,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.260000,80.260
48,Lando Norris,75.096,NOR,NOR,0 days 00:01:19.915000,79.915
49,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.151000,80.151
50,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.261000,80.261
51,Lando Norris,75.096,NOR,NOR,0 days 00:01:19.959000,79.959
52,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.267000,80.267
53,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.107000,80.107
54,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.294000,80.294
55,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.481000,80.481
56,Lando Norris,75.096,NOR,NOR,0 days 00:01:20.571000,80.571
57,Lando Norris,75.096,NOR,NOR,0 days 00:01:50.655000,110.655
58,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:31.036000,91.036
59,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:23.232000,83.232
60,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.669000,82.669
61,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.581000,82.581
62,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.594000,82.594
63,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.582000,82.582
64,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.877000,82.877
65,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:23.052000,83.052
66,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:36.501000,96.501
67,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:27.799000,87.799
68,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.728000,82.728
69,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.948000,82.948
70,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.426000,82.426
71,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.968000,81.968
72,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.961000,81.961
73,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.015000,82.015
74,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:36.822000,96.822
75,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:28.994000,88.994
76,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.871000,81.871
77,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.085000,82.085
78,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.923000,81.923
79,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.013000,82.013
80,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.817000,81.817
81,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.830000,81.830
82,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.597000,81.597
83,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.243000,82.243
84,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.287000,82.287
85,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.204000,82.204
86,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:23.479000,83.479
87,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.520000,82.520
88,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.133000,82.133
89,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.989000,81.989
90,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.100000,82.100
91,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.238000,82.238
92,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.059000,82.059
93,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:22.047000,82.047
94,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.890000,81.890
95,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:25.203000,85.203
96,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:36.781000,96.781
97,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:26.930000,86.930
98,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.424000,81.424
99,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:21.080000,81.080
100,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.485000,80.485
101,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.395000,80.395
102,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.223000,80.223
103,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.615000,80.615
104,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.682000,80.682
105,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.588000,80.588
106,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.352000,80.352
107,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.496000,80.496
108,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.718000,80.718
109,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.295000,80.295
110,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.308000,80.308
111,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.199000,80.199
112,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.754000,80.754
113,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:20.357000,80.357
114,Oscar Piastri,75.180,PIA,PIA,0 days 00:01:25.255000,85.255
115,Oscar Piastri,75.180,PIA,PIA,0 days 00:02:04.363000,124.363
116,Max Verstappen,75.481,VER,VER,0 days 00:01:27.458000,87.458
117,Max Verstappen,75.481,VER,VER,0 days 00:01:24.099000,84.099
118,Max Verstappen,75.481,VER,VER,0 days 00:01:23.115000,83.115
119,George Russell,75.546,RUS,RUS,0 days 00:01:31.910000,91.910
120,George Russell,75.546,RUS,RUS,0 days 00:01:23.347000,83.347
121,George Russell,75.546,RUS,RUS,0 days 00:01:23.037000,83.037
122,George Russell,75.546,RUS,RUS,0 days 00:01:23.571000,83.571
123,George Russell,75.546,RUS,RUS,0 days 00:01:23.172000,83.172
124,George Russell,75.546,RUS,RUS,0 days 00:01:23.119000,83.119
125,George Russell,75.546,RUS,RUS,0 days 00:01:22.764000,82.764
126,George Russell,75.546,RUS,RUS,0 days 00:01:36.920000,96.920
127,George Russell,75.546,RUS,RUS,0 days 00:01:28.331000,88.331
128,George Russell,75.546,RUS,RUS,0 days 00:01:22.737000,82.737
129,George Russell,75.546,RUS,RUS,0 days 00:01:22.716000,82.716
130,George Russell,75.546,RUS,RUS,0 days 00:01:23.022000,83.022
131,George Russell,75.546,RUS,RUS,0 days 00:01:23.438000,83.438
132,George Russell,75.546,RUS,RUS,0 days 00:01:23.390000,83.390
133,George Russell,75.546,RUS,RUS,0 days 00:01:24.086000,84.086
134,George Russell,75.546,RUS,RUS,0 days 00:01:23.366000,83.366
135,George Russell,75.546,RUS,RUS,0 days 00:01:41.485000,101.485
136,George Russell,75.546,RUS,RUS,0 days 00:01:27.166000,87.166
137,George Russell,75.546,RUS,RUS,0 days 00:01:22.400000,82.400
138,George Russell,75.546,RUS,RUS,0 days 00:01:22.434000,82.434
139,George Russell,75.546,RUS,RUS,0 days 00:01:23.429000,83.429
140,George Russell,75.546,RUS,RUS,0 days 00:01:22.838000,82.838
141,George Russell,75.546,RUS,RUS,0 days 00:01:23.012000,83.012
142,George Russell,75.546,RUS,RUS,0 days 00:01:22.942000,82.942
143,George Russell,75.546,RUS,RUS,0 days 00:01:22.703000,82.703
144,George Russell,75.546,RUS,RUS,0 days 00:01:22.885000,82.885
145,George Russell,75.546,RUS,RUS,0 days 00:01:23.138000,83.138
146,George Russell,75.546,RUS,RUS,0 days 00:01:23.096000,83.096
147,George Russell,75.546,RUS,RUS,0 days 00:01:22.663000,82.663
148,George Russell,75.546,RUS,RUS,0 days 00:01:22.663000,82.663
149,George Russell,75.546,RUS,RUS,0 days 00:01:22.515000,82.515
150,George Russell,75.546,RUS,RUS,0 days 00:01:22.710000,82.710
151,George Russell,75.546,RUS,RUS,0 days 00:01:22.461000,82.461
152,George Russell,75.546,RUS,RUS,0 days 00:01:22.353000,82.353
153,George Russell,75.546,RUS,RUS,0 days 00:01:22.591000,82.591
154,George Russell,75.546,RUS,RUS,0 days 00:01:22.537000,82.537
155,George Russell,75.546,RUS,RUS,0 days 00:01:22.408000,82.408
156,George Russell,75.546,RUS,RUS,0 days 00:01:22.175000,82.175
157,George Russell,75.546,RUS,RUS,0 days 00:01:22.167000,82.167
158,George Russell,75.546,RUS,RUS,0 days 00:01:22.473000,82.473
159,George Russell,75.546,RUS,RUS,0 days 00:01:22.319000,82.319
160,George Russell,75.546,RUS,RUS,0 days 00:01:22.257000,82.257
161,George Russell,75.546,RUS,RUS,0 days 00:01:22.111000,82.111
162,George Russell,75.546,RUS,RUS,0 days 00:01:22.097000,82.097
163,George Russell,75.546,RUS,RUS,0 days 00:01:36.343000,96.343
164,George Russell,75.546,RUS,RUS,0 days 00:01:26.434000,86.434
165,George Russell,75.546,RUS,RUS,0 days 00:01:20.326000,80.326
166,George Russell,75.546,RUS,RUS,0 days 00:01:20.739000,80.739
167,George Russell,75.546,RUS,RUS,0 days 00:01:20.808000,80.808
168,George Russell,75.546,RUS,RUS,0 days 00:01:20.982000,80.982
169,George Russell,75.546,RUS,RUS,0 days 00:01:20.695000,80.695
170,George Russell,75.546,RUS,RUS,0 days 00:01:20.529000,80.529
171,George Russell,75.546,RUS,RUS,0 days 00:01:20.284000,80.284
172,George Russell,75.546,RUS,RUS,0 days 00:01:21.194000,81.194
173,George Russell,75.546,RUS,RUS,0 days 00:01:20.791000,80.791
174,George Russell,75.546,RUS,RUS,0 days 00:01:20.655000,80.655
175,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:33.305000,93.305
176,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.807000,83.807
177,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.203000,83.203
178,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.434000,83.434
179,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.310000,83.310
180,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.445000,83.445
181,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.864000,82.864
182,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.381000,83.381
183,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:38.210000,98.210
184,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:29.892000,89.892
185,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.898000,82.898
186,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.799000,82.799
187,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.032000,83.032
188,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.823000,82.823
189,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.336000,83.336
190,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.252000,83.252
191,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:43.577000,103.577
192,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:24.892000,84.892
193,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.994000,82.994
194,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.048000,83.048
195,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.968000,82.968
196,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.673000,82.673
197,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.953000,82.953
198,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.026000,83.026
199,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.001000,83.001
200,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.302000,83.302
201,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.248000,83.248
202,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.075000,83.075
203,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.498000,83.498
204,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.382000,83.382
205,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.367000,83.367
206,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.390000,83.390
207,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.226000,83.226
208,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.323000,83.323
209,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.289000,83.289
210,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:37.156000,97.156
211,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:29.144000,89.144
212,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.924000,81.924
213,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:22.247000,82.247
214,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:23.218000,83.218
215,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.764000,81.764
216,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.784000,81.784
217,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.928000,81.928
218,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.824000,81.824
219,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.696000,81.696
220,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.134000,81.134
221,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.254000,81.254
222,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.174000,81.174
223,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.303000,81.303
224,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.285000,81.285
225,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.568000,81.568
226,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.647000,81.647
227,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.553000,81.553
228,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.716000,81.716
229,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.677000,81.677
230,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:21.812000,81.812
231,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:44.371000,104.371
232,Yuki Tsunoda,75.670,TSU,TSU,0 days 00:01:54.042000,114.042
233,Alexander Albon,75.737,ALB,ALB,0 days 00:01:35.752000,95.752
234,Alexander Albon,75.737,ALB,ALB,0 days 00:01:24.536000,84.536
235,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.606000,83.606
236,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.438000,83.438
237,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.916000,83.916
238,Alexander Albon,75.737,ALB,ALB,0 days 00:01:37.861000,97.861
239,Alexander Albon,75.737,ALB,ALB,0 days 00:01:28.447000,88.447
240,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.720000,83.720
241,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.645000,83.645
242,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.852000,83.852
243,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.254000,83.254
244,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.767000,82.767
245,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.183000,83.183
246,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.978000,82.978
247,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.027000,83.027
248,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.963000,82.963
249,Alexander Albon,75.737,ALB,ALB,0 days 00:01:44.306000,104.306
250,Alexander Albon,75.737,ALB,ALB,0 days 00:01:24.344000,84.344
251,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.022000,83.022
252,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.607000,82.607
253,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.066000,83.066
254,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.301000,83.301
255,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.198000,83.198
256,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.513000,83.513
257,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.671000,83.671
258,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.525000,83.525
259,Alexander Albon,75.737,ALB,ALB,0 days 00:01:37.440000,97.440
260,Alexander Albon,75.737,ALB,ALB,0 days 00:01:29.209000,89.209
261,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.792000,82.792
262,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.898000,82.898
263,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.949000,82.949
264,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.901000,82.901
265,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.188000,83.188
266,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.061000,83.061
267,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.135000,83.135
268,Alexander Albon,75.737,ALB,ALB,0 days 00:01:24.486000,84.486
269,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.918000,82.918
270,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.154000,82.154
271,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.011000,82.011
272,Alexander Albon,75.737,ALB,ALB,0 days 00:01:21.740000,81.740
273,Alexander Albon,75.737,ALB,ALB,0 days 00:01:23.574000,83.574
274,Alexander Albon,75.737,ALB,ALB,0 days 00:01:21.730000,81.730
275,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.292000,82.292
276,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.499000,82.499
277,Alexander Albon,75.737,ALB,ALB,0 days 00:01:21.907000,81.907
278,Alexander Albon,75.737,ALB,ALB,0 days 00:01:21.618000,81.618
279,Alexander Albon,75.737,ALB,ALB,0 days 00:01:21.845000,81.845
280,Alexander Albon,75.737,ALB,ALB,0 days 00:01:21.927000,81.927
281,Alexander Albon,75.737,ALB,ALB,0 days 00:01:21.918000,81.918
282,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.219000,82.219
283,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.319000,82.319
284,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.184000,82.184
285,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.399000,82.399
286,Alexander Albon,75.737,ALB,ALB,0 days 00:01:24.131000,84.131
287,Alexander Albon,75.737,ALB,ALB,0 days 00:01:22.312000,82.312
288,Alexander Albon,75.737,ALB,ALB,0 days 00:01:24.190000,84.190
289,Alexander Albon,75.737,ALB,ALB,0 days 00:01:50.408000,110.408
290,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:30.520000,90.520
291,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:23.014000,83.014
292,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.776000,82.776
293,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.519000,82.519
294,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.632000,82.632
295,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.673000,82.673
296,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.684000,82.684
297,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.983000,82.983
298,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:36.036000,96.036
299,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:27.861000,87.861
300,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.647000,82.647
301,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.841000,81.841
302,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.222000,82.222
303,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.952000,81.952
304,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.735000,81.735
305,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.247000,82.247
306,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:37.435000,97.435
307,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:28.896000,88.896
308,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.881000,81.881
309,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.885000,81.885
310,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.058000,82.058
311,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.722000,81.722
312,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.932000,81.932
313,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.852000,81.852
314,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:21.951000,81.951
315,Charles Leclerc,75.755,LEC,LEC,0 days 00:01:22.042000,82.042